//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        public string IDBill { get; set; }
        public string MaNV { get; set; }
        public Nullable<int> MaDV { get; set; }
        public string IDTK { get; set; }
        public string IDOrder { get; set; }
        public Nullable<int> TongTien { get; set; }
    
        public virtual DichVuKH DichVuKH { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual KHorder KHorder { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
