//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class may
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public may()
        {
            this.KHorders = new HashSet<KHorder>();
        }
        public List<ListFoodOrder> Listorder { get; set; }
        public string MaMay { get; set; }
        public string TenMay { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public int Phong { get; set; }
        public string IDTK { get; set; }
        public string IPcLient { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHorder> KHorders { get; set; }
        public virtual Phong Phong1 { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
